config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users
  root 'home#landing'
  get 'about_us' => 'home#about_us' 
  get 'contact' => 'home#contact'
  get 'legal/privacy'
  get 'legal/terms_of_use' => 'legal#terms' 
  get 'legal/cookies'
  get 'legal/social_networks'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing
     @user = User.new
  end

  def about_us
  end

  def contact
  end
end

app/controllers/legal_controller.rb
class LegalController < ApplicationController
  def privacy
  end

  def terms
  end

  def cookies
  end

  def social_networks
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :sku, :price, :description, :picture)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.with(user: @user).welcome.deliver_later
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/legal_helper.rb
module LegalHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about_us.html.erb
<h1>Home#about_us</h1>
<p>Find me in app/views/home/about_us.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/landing.html.erb
<h1>Home#landing</h1>
<p>Find me in app/views/home/landing.html.erb</p>
<%= render 'users/subscribe_form', user: @user %>
<p><strong><font color="brown">Esta es la home</font></strong></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
<link rel="preconnect" href="https://app.snipcart.com">
<link rel="preconnect" href="https://cdn.snipcart.com">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css" />
   
  </head>

  <body>
    <H3><strong><font color="black">MENU:</font></strong></H3> 
    <nav>
      <ul>
          <li><%= link_to 'home', root_path %></li>
           <li><%= link_to 'users (admin)', users_path %></li>
            <li><%= link_to 'Store', products_path %></li>
          <li><%= link_to 'about us', about_us_path %></li>
          <li><%= link_to 'contact', contact_path %></li>
       </ul>
    </nav>
    <br>
    <%= yield %>
    <footer>
      <ul>
        <li><%= link_to 'privacy', legal_privacy_path %></li>
        <li><%= link_to 'terms of use', legal_terms_of_use_path %></li>
        <li><%= link_to 'cookies', legal_cookies_path %></li>
        <li><%= link_to 'social networks', legal_social_networks_path %></li>
      </ul>
    </footer>
    
    <script async src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js"></script>
    <div hidden id="snipcart" data-api-key="MjU3MzUwYWEtZTk0Mi00NGIzLTg0ODktNDAyY2QwMjI2MzEwNjM3NTg1Mzk3MjA4MTYxOTQx"></div>
    
  </body>
</html>

app/views/legal/cookies.html.erb
<h1>Legal#cookies</h1>
<p>Find me in app/views/legal/cookies.html.erb</p>

app/views/legal/privacy.html.erb
<h1>Legal#privacy</h1>
<p>Find me in app/views/legal/privacy.html.erb</p>

app/views/legal/social_networks.html.erb
<h1>Legal#social_networks</h1>
<p>Find me in app/views/legal/social_networks.html.erb</p>

app/views/legal/terms.html.erb
<h1>Legal#terms</h1>
<p>Find me in app/views/legal/terms.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  
  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1>PRODUCTS</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th><u>Name</u></th>
      <th><u>Sku</u></th>
      <th><u>Price</u></th>
      <th><u>Description</u></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <% if product.picture.attached? %>
            <%= image_tag product.picture, alt: "Picture", class: "picture nano" %>
          <% end %>
        </td>
        <td><%= product.name %></td>
        <td><%= product.sku %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td>
          <button class="snipcart-add-item"
            data-item-id="<%= product.sku %>"
            data-item-price="<%= product.price %>"
            data-item-url="<%= url_for(product) %>"
            data-item-description="<%= product.description %>"
            data-item-image="<%= url_for(product.picture) %>"
            data-item-name="<%= product.name %>">
           <font color="red"><strong> Add to cart</strong></font>
          </button>
        </td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% if @product.picture.attached? %>
 <%= image_tag @product.picture, alt: "Picture", class: "picture" %>
 <% end %>
 
<button class="snipcart-add-item"
  data-item-id="<%= @product.sku %>"
  data-item-price="<%= @product.price %>"
  data-item-url="<%= url_for(@product) %>"
  data-item-description="<%= @product.description %>"
  data-item-image="<%= url_for(@product.picture) %>"
  data-item-name="<%= @product.name %>">
 Add to cart
 </button>
 
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>
  
  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  
   <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_subscribe_form.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit 'Suscríbete'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>USERS</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th><u>Firstname</u></th>
      <th><u>Lastname</u></th>
      <th><u>Email</u></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
           <% if user.avatar.attached? %>
              <%= image_tag user.avatar, alt: "Avatar", class: "avatar nano" %>
           <% end %>
        </td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @user.avatar.attached? %>
 <%= image_tag @user.avatar, alt: "Avatar", class: "avatar" %>
 <% end %>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>